### ISSUE TITLE
Add typings for react-dom

### ISSUE THREAD

**Issue by unional** [cantide5ga/typed-react#1]
Since it is part of `react` (not a separate npm package), and it reuse definitions in `react`, we can create the `react-dom` typings directly in this repo?

What do you think @blakeembrey?

**Comment by unional** [comment]
Referencing:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/react/react-dom.d.ts

**Comment by blakeembrey** [comment]
@unional Actually, it is a separate NPM package - https://www.npmjs.com/package/react-dom.

**Comment by unional** [comment]
oh...... why I always get the wrong information~~ 😡 

https://github.com/facebook/react#installation
Script section add both but npm section only `npm i --save react`

and then here
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/react/react-dom.d.ts#L2
also just point to `react`....

sorry about the noise.
