### ISSUE TITLE
Update typings registry

### ISSUE THREAD

**Issue by katainaka0503** [cantide5ga/typed-react#7]
Since Typings registry refers to old hash, compilation errors occur when I enable "noImplicitAny".

**Comment by cantide5ga** [comment]
@katainaka0503 are you saying that updating locally to latest hash fixes this for you?

**Comment by katainaka0503** [comment]
@cantide5ga Yes. 
I'm sorry for my poor explanation. 
I meant this merge should be reflected in typings registry. #4

**Comment by cantide5ga** [comment]
@katainaka0503 see short discussion here #4 if you have anything to add.  Looks like I'll be taking care of this myself shortly.

If this is actually an issue with `noImplicitAny`, let me know.

**Comment by katainaka0503** [comment]
@cantide5ga Thanks for reply.
This is actually an issue with noImplicitAny.

**Comment by cantide5ga** [comment]
@katainaka0503 so should I reopen?  These type definitions use `any` all over, so not understanding how updating the registry commit would fix this.  Have you actually seen this work locally?

**Comment by katainaka0503** [comment]
I think yes.
I have tried this locally.
With new hash, compilation error doesn't occur when JSX is passed to ReactDOM.render().
But, with the hash which typings refers to, error( `JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists` ) occurs.

**Comment by katainaka0503** [comment]
@cantide5ga Thank you very much for processing my request!
